configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://ep-red-shadow-73703154.us-east-2.aws.neon.tech/neondb?user=Savinvadim1312&password=jTeWkxzRQ65s
  - configuration:
      name: auth_config
      client_id: 9ff893e0b8a84a27846533199a9b7370
      client_secret: cd39d51d34e74734aedbeacaf824ff59